### ISSUE TITLE
Request for details on minimised notification

### ISSUE THREAD

**Issue by ChaudhariSumit** [sweakpl/unlock-master#7]
I have minimised the notification.
It shows app name when minimised.
I want to request to add some useful details from the actual notification, to the minimised notification.
![20240411_160145](https://github.com/sweakpl/unlock-master/assets/23293531/14b20e88-2b0e-4748-a852-bf524f4362ad)

Reference app from above screenshot
https://f-droid.org/packages/ca.chancehorizon.paseo/

**Comment by sweakpl** [comment]
Hey, thanks for reporting! This makes much sense and I will take your suggestion into account while preparing the next update.
